version = 1

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/Pharaoh2216/AllahAsMyWitness"
  dependencies_vendored = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "meteor",
    "angularjs",
    "react",
    "vue",
    "ember",
    "angular"
  ]

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "scala"
enabled = true

[[analyzers]]
name = "rust"
enabled = true

[[transformers]]
name = "google-java-format"
enabled = true

[[transformers]]
name = "autopep8"
enabled = true

[[transformers]]
name = "php-cs-fixer"
enabled = true

[[transformers]]
name = "standardrb"
enabled = true
